### ISSUE TITLE
Light mode is not woring in the react 

### ISSUE THREAD

**Issue by jashandeep31** [super-turbo-stack/create-super-turbo#52]
When we create a react app due to the wrong config of the shadcn UI  CSS file light mode does not work even with the themes.

Try to recreate the issue
1. create a new app 
with express and the react app 

then try to change the theme from dark to the light either manually or using the theming provider from the shadcn

refer video https://www.youtube.com/watch?v=YJr2No5pPbw

**Comment by ofcljaved** [comment]
Thank you for raising your issue regarding the theming setup in our CLI application. 

By default, our CLI app configures a React and Next.js application similar to a basic Next.js setup with Tailwind CSS. In this configuration, theming is determined by system preferences rather than using classes, as implemented in ShadCN.

If you have set up ShadCN in Next.js via their CLI, you may notice that they modify the `style.css` and `tailwind.config.js` files to include the `darkMode` property set to `class`. This enables class-based theming. Additionally, within their theme provider, they implement a `useEffect` hook that checks the system theme using JavaScript and adjusts the classes accordingly.

To enable theming based solely on the `prefers-color-scheme` media query, we opted not to include the theme provider in our demo setup. Instead, we configured our CSS and Tailwind accordingly.

For users who wish to utilize ShadCN's theming capabilities, we have included the `.dark` property in the CSS file. To achieve this, simply remove the media scheme and adjust your Tailwind configuration as needed.

Also you can checkout this repository for theming via ShadCN [with-theming](https://github.com/super-turbo-stack/with-theming)

Lastly, I noticed a minor spelling error in your issue description. The term "woring" should be corrected to "working." Attention to detail helps maintain clarity in our communication.

Thank you for your understanding, and please feel free to reach out if you have any further questions or need assistance!
